queryParameters:
  page:
    description: The current page of phone book entries.
    type: integer
    minimum: 1
    default: 1
  perPage:
    description: The nunber of entries per page.
    type: integer
    minimum: 5
    maximum: 25
    default: 5
